// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeNimgeOyphyjQIlVNbZe1Zt0wt7qVBvw',
    appId: '1:899337678586:web:10372bfc06fbd084daa343',
    messagingSenderId: '899337678586',
    projectId: 'shop-me-a0321',
    authDomain: 'shop-me-a0321.firebaseapp.com',
    storageBucket: 'shop-me-a0321.firebasestorage.app',
    measurementId: 'G-QKQ1B7TSWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAucyKJEq4uk9oVQDpYq74lgxKRFozGKUc',
    appId: '1:899337678586:android:88ee98b54b6dd3d4daa343',
    messagingSenderId: '899337678586',
    projectId: 'shop-me-a0321',
    storageBucket: 'shop-me-a0321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcZFQZRKrdpXFLDVmd3aTCClvmoxIS6MU',
    appId: '1:899337678586:ios:947173e6f924c157daa343',
    messagingSenderId: '899337678586',
    projectId: 'shop-me-a0321',
    storageBucket: 'shop-me-a0321.firebasestorage.app',
    iosBundleId: 'com.example.captureCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcZFQZRKrdpXFLDVmd3aTCClvmoxIS6MU',
    appId: '1:899337678586:ios:947173e6f924c157daa343',
    messagingSenderId: '899337678586',
    projectId: 'shop-me-a0321',
    storageBucket: 'shop-me-a0321.firebasestorage.app',
    iosBundleId: 'com.example.captureCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeNimgeOyphyjQIlVNbZe1Zt0wt7qVBvw',
    appId: '1:899337678586:web:46c5310a4e8b11eddaa343',
    messagingSenderId: '899337678586',
    projectId: 'shop-me-a0321',
    authDomain: 'shop-me-a0321.firebaseapp.com',
    storageBucket: 'shop-me-a0321.firebasestorage.app',
    measurementId: 'G-54P59378GW',
  );
}
